# TierService Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore ApiMonetizationGateway.sln
RUN dotnet publish Gateway/TierService/ApiMonetizationGateway.TierService/ApiMonetizationGateway.TierService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5055
ENV ASPNETCORE_URLS=http://0.0.0.0:5055
ENTRYPOINT ["dotnet", "ApiMonetizationGateway.TierService.dll"]
