version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=MonetizationGatewayDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - JWT__KEY=ThisIsMySecretKeyForJWTTokenGenerationAndShouldBeAtLeast256Bits
      - JWT__ISSUER=ApiMonetizationGateway
      - JWT__AUDIENCE=ApiMonetizationGatewayUsers
    ports:
      - "5000:5000"
    depends_on:
      - sql
      - redis
      - rabbitmq
      - userservice
      - tierservice
      - billingservice
      - usage
  userservice:
    build:
      context: .
      dockerfile: Dockerfile.userservice
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=MonetizationGatewayDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5001:5001"
    depends_on:
      - sql
      - redis
  tierservice:
    build:
      context: .
      dockerfile: Dockerfile.tierservice
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=MonetizationGatewayDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true
    ports:
      - "5055:5055"
    depends_on:
      - sql
  billingservice:
    build:
      context: .
      dockerfile: Dockerfile.billingservice
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=MonetizationGatewayDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true
    ports:
      - "5004:5004"
    depends_on:
      - sql
  usage:
    build:
      context: .
      dockerfile: Dockerfile.usage
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=MonetizationGatewayDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__HostName=rabbitmq
    ports:
      - "5287:5287"
    depends_on:
      - sql
      - redis
      - rabbitmq
